---
title: "Tables and Figures"
---

```{r, echo=FALSE}
library(knitr)
library(ggplot2)
```

```{r, echo=FALSE}
my_data <- data.frame(
  Name = c("Indicator", "Group 1", "Group 2", "Group 1 Subgroups", "Group 2 Subgroups", "Time", "Value"),
  Details = c("Needed Counseling or Therapy But Did Not Get It, Last 4 Weeks", "Age", "Education", "7 age subgroups", "4 education subgroups", "Year, Month", "Percent")
)
kable(my_data, caption = "Table 2. List of Relevant Columns Examined")
```

```{r, echo=FALSE}
ggplot(age_subgrp_nocare_mean, aes(x = Subgroup, y = mean_value, fill = Subgroup)) +
  geom_bar(stat = "identity") +
  labs(
    title = "Figure 1. Average Percent of Individuals Lacking Mental Health Counseling or Therapy by Age", 
    x = "Age Group", 
    y = "Average Percent"
    ) +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(size = 12))
```

```{r, echo=FALSE}
#Age + Year 
age_subgrp_nocare_mean_yr <- age_subgrp_nocare %>%
  group_by(year, Subgroup) %>%
  summarize(mean_value = mean(Value, na.rm = TRUE), .groups = "drop")

ggplot(age_subgrp_nocare_mean_yr, aes(x = year, y = mean_value, color = Subgroup)) +
  geom_line() +
  labs(
    title = "Figure 2. Percent of Individuals Lacking Mental Health Counseling or Therapy by Age from 2020 to 2022",
    x = "Year",
    y = "Percent"
  ) +
  theme_minimal() + 
  theme(plot.title = element_text(size = 12)) + 
  scale_x_continuous(breaks = unique(age_subgrp_nocare_mean_yr$year), labels = unique(age_subgrp_nocare_mean_yr$year))
```

```{r, echo=FALSE}
#reorder Subgroups on graph
custom_order <- c("Less than a high school diploma", "High school diploma or GED", "Some college/Associate's degree", "Bachelor's degree or higher")

edu_subgrp_nocare_mean$Subgroup <- factor(edu_subgrp_nocare_mean$Subgroup, levels = custom_order)

ggplot(edu_subgrp_nocare_mean, aes(x = Subgroup, y = mean_value, fill = Subgroup)) +
  geom_bar(stat = "identity") +
  labs(
    title = "Figure 3. Average Percent of Individuals Lacking Mental Health Counseling or Therapy by Education Level", 
    x = "Education Level", 
    y = "Average Percent"
    ) +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(size = 12))
```

```{r, echo=FALSE}
#Edu by Year
edu_subgrp_nocare_mean_yr <- edu_subgrp_nocare %>%
  group_by(year, Subgroup) %>%
  summarize(mean_value = mean(Value, na.rm = TRUE), .groups = "drop")

#reorder Subgroups on graph
custom_order <- c("Less than a high school diploma", "High school diploma or GED", "Some college/Associate's degree", "Bachelor's degree or higher")

edu_subgrp_nocare_mean_yr$Subgroup <- factor(edu_subgrp_nocare_mean_yr$Subgroup, levels = custom_order)

ggplot(edu_subgrp_nocare_mean_yr, aes(x = year, y = mean_value, color = Subgroup)) +
  geom_line() +
  labs(
    title = "Figure 4. Average Percent of Individuals Lacking Mental Health Counseling or Therapy by Education Level from 2020 to 2022",
    x = "Year",
    y = "Percent"
  ) +
  theme_minimal() + 
  theme(plot.title = element_text(size = 12)) + 
  scale_x_continuous(breaks = unique(edu_subgrp_nocare_mean_yr$year), labels = unique(edu_subgrp_nocare_mean_yr$year))
```

```{r, echo=FALSE}
ggplot(yr_nocare_mean, aes(x = year, y = mean_value)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Figure 5. Average Percent of Individuals Lacking Mental Health Counseling or Therapy per Year from 2020 to 2022",
    x = "Year",
    y = "Average Percent"
  ) +
  theme_minimal() + 
  theme(plot.title = element_text(size = 12)) + 
  scale_x_continuous(breaks = unique(yr_nocare_mean$year), labels = unique(yr_nocare_mean$year))
```

```{r, echo=FALSE}
# month_names <- data.frame(month = 1:12, month_name = month.name)
mo_nocare_mean$month <- factor(mo_nocare_mean$month, levels = 1:12, labels = month.name)

ggplot(mo_nocare_mean, aes(x = month, y = mean_value, group = 1)) +
  geom_line() +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  labs(
    title = "Figure 6. Average Percent of Individuals Lacking Mental Health Counseling or Therapy per Month from 2020 to 2022",
    x = "Months",
    y = "Mean Value"
  ) +
  theme_minimal() + 
  # scale_x_discrete(
  #   breaks = month_names$month,
  #   labels = month_names$month_name)
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(size = 12))
```
