<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Shirley Li">

<title>PM566 Final - Full Report</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">PM566 Final</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html" rel="" target="">
 <span class="menu-text">Background</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./figures.html" rel="" target="">
 <span class="menu-text">Tables and Figures</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Final.html" rel="" target="" aria-current="page">
 <span class="menu-text">Full Report</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#trends-in-lack-of-mental-health-care-since-the-covid-19-pandemic" id="toc-trends-in-lack-of-mental-health-care-since-the-covid-19-pandemic" class="nav-link active" data-scroll-target="#trends-in-lack-of-mental-health-care-since-the-covid-19-pandemic">Trends in Lack of Mental Health Care Since the COVID-19 Pandemic</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question">Research Question</a></li>
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background">Background</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  </ul></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a>
  <ul class="collapse">
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling">Data Wrangling</a></li>
  <li><a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda">Exploratory Data Analysis (EDA)</a></li>
  </ul></li>
  <li><a href="#resultsdata-visualization" id="toc-resultsdata-visualization" class="nav-link" data-scroll-target="#resultsdata-visualization">Results/Data Visualization</a>
  <ul class="collapse">
  <li><a href="#age-1" id="toc-age-1" class="nav-link" data-scroll-target="#age-1">Age</a></li>
  <li><a href="#education-1" id="toc-education-1" class="nav-link" data-scroll-target="#education-1">Education</a></li>
  <li><a href="#year-and-month" id="toc-year-and-month" class="nav-link" data-scroll-target="#year-and-month">Year and Month</a></li>
  </ul></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Full Report</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Shirley Li </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="trends-in-lack-of-mental-health-care-since-the-covid-19-pandemic" class="level1">
<h1>Trends in Lack of Mental Health Care Since the COVID-19 Pandemic</h1>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<section id="research-question" class="level3">
<h3 class="anchored" data-anchor-id="research-question">Research Question</h3>
<p>Is there a trend in individuals in the United States that need counseling or therapy for mental health disorders but did not receive relevant care? Is there a difference between different demographics (age, education status) and/or between different years (2022, 2021, 2020) and months within the year?</p>
</section>
<section id="background" class="level3">
<h3 class="anchored" data-anchor-id="background">Background</h3>
<p>Mental health is becoming an increasing concern since the 2019 coronavirus pandemic, with heightened stress, fear, and loneliness, along with elevated rates of “anxiety, anger, confusion, and posttraumatic symptoms” (Khan et al., 2022; Pakpour and Griffiths, 2020; Christoffersen et al., 2023). Though not discounting community and individual resilience in the face of these difficulties, overall the pandemic appears to have negative impacts on psychological health across the board (Mills et al., 2022). Many contributing factors have been identified in literature, including social distancing, social isolation, quarantine, and misinformation (Khan et al., 2022; Ahorsu et al., 2020; Sakib et al., 2020). In light of this, variation in experiences across different groups may be important to further examine to better understand the intricacies within these cohorts. More specifically, by identifying cohorts that may not be receiving care needed, barriers to access and resources may be more clearly outlined and show insight into the development of potentially more effective targeted therapies and care options to promote improved health of all populations.</p>
<p>Different age groups may be understood to have had variety of experience in the context of policies and regulations – for instance, college-age adults experienced closure of university campuses, along with lack of in-person events and ceremonies (e.g.&nbsp;orientations and graduations). On the other hand, many working adults had to transition to remote working environments along with parents of young children struggling to balance childcare at home without in-person schools, while essential workers were subject to high-stress environments and lack of resources during this time. Senior isolation was a rising issue, along with lack of health care and access for chronic diseases. While the resulting psychological pressures of these experiences may not necessarily be specific to any one age group, it may play a role in possible differences in rates of mental health disorders and treatment since then. Additionally, with misinformation being rampant and a large factor for many in their decision-making process during the pandemic, education status may be a significant component influencing prevalence of mental health disorders and treatment access during this time.</p>
<p>With the evolution of the pandemic since 2019, along with administration of vaccinations, political transitions and economic rises/falls, and almost normalization of the pandemic-induced experience, it is also worth examining any potential trends in mental health disorders and treatments over time.</p>
</section>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>This data is acquired from the CDC (Centers for Disease Control and Prevention) Household Pulse Surveys, an experimental data system created by partnership between the National Center for Health Statistics (NCHC) and the U.S. Census Bureau along with other federal agencies. The intention was to “rapidly respond and provide relevant information about the impact of the coronavirus pandemic in the U.S. Data collection” beginning April 23, 2020. Specifically, this dataset is called “Mental Health Care in the Last 4 Weeks” where each four week period was a collection time point. The surveys were disseminated online, via email and text message with randomized selection of participants contacted to respond for each linked household. Sample sizes for each measured time period of 4 weeks range from 50,000 to 93,000, with weights response rates from 5.80% to 10.30%. (See https://www.cdc.gov/nchs/covid19/pulse/mental-health-care.htm for more information.)</p>
</section>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<section id="data-wrangling" class="level3">
<h3 class="anchored" data-anchor-id="data-wrangling">Data Wrangling</h3>
<p>In the original dataset, there are a total of 15 columns and 10404 rows. The rows are divided into four uniquely labelled sections with respect to Indicators, with 2601 records per section.</p>
<p>See Table 1a. for more details regarding the columns. There are a number of missing measures noted for the column of interest “Value”. This is due to the way the data was collected: there are a number of time phases during which the data is recorded, with a “break week” in between every 4th week (labelled as “Phase -1” for that column). As such, when examining closer, this results in an offset in time measurements seen (i.e., measured times are not exactly every 4 weeks or necessarily starting in the first week of each month; rather it looks more similar to a pattern of every 5 weeks) which may have some influence on the differences in total measures per year and month.</p>
<p>See Table 1b. for more details regarding the rows. See Table 1c. through 1e. for more details regarding methods in identification of relevant rows and columns.</p>
<p>For the purpose of this project and research question, I will be focusing on select columns. See Table 2. for more details.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 10404 Columns: 15
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (10): Indicator, Group, State, Subgroup, Phase, Time Period Label, Time ...
dbl  (5): Time Period, Value, LowCI, HighCI, Suppression Flag

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table 1a. List of Columns in the Dataset and Counts</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Column</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Indicator</td>
<td style="text-align: right;">10404</td>
</tr>
<tr class="even">
<td style="text-align: left;">Group</td>
<td style="text-align: right;">10404</td>
</tr>
<tr class="odd">
<td style="text-align: left;">State</td>
<td style="text-align: right;">10404</td>
</tr>
<tr class="even">
<td style="text-align: left;">Subgroup</td>
<td style="text-align: right;">10404</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Phase</td>
<td style="text-align: right;">10404</td>
</tr>
<tr class="even">
<td style="text-align: left;">Time Period</td>
<td style="text-align: right;">10404</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Time Period Label</td>
<td style="text-align: right;">10404</td>
</tr>
<tr class="even">
<td style="text-align: left;">Time Period Start Date</td>
<td style="text-align: right;">10404</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Time Period End Date</td>
<td style="text-align: right;">10404</td>
</tr>
<tr class="even">
<td style="text-align: left;">Value</td>
<td style="text-align: right;">9914</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LowCI</td>
<td style="text-align: right;">9914</td>
</tr>
<tr class="even">
<td style="text-align: left;">HighCI</td>
<td style="text-align: right;">9914</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Confidence Interval</td>
<td style="text-align: right;">9914</td>
</tr>
<tr class="even">
<td style="text-align: left;">Quartile Range</td>
<td style="text-align: right;">6732</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Suppression Flag</td>
<td style="text-align: right;">22</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>To determine the columns relevant to my research question as shown in Table 2., I first determined how many potential indicators (i.e.&nbsp;mental health treatment), as well as groups and subgroups, were available.</p>
<p>There are 4 different indicators.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table 1b. List of Unique Indicators and Counts</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Row</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Took Prescription Medication for Mental Health, Last 4 Weeks</td>
<td style="text-align: right;">2601</td>
</tr>
<tr class="even">
<td style="text-align: left;">Received Counseling or Therapy, Last 4 Weeks</td>
<td style="text-align: right;">2601</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Took Prescription Medication for Mental Health And/Or Received Counseling or Therapy, Last 4 Weeks</td>
<td style="text-align: right;">2601</td>
</tr>
<tr class="even">
<td style="text-align: left;">Needed Counseling or Therapy But Did Not Get It, Last 4 Weeks</td>
<td style="text-align: right;">2601</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>There are 10 different groups.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table 1c. List of Unique Groups</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Group</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">National Estimate</td>
</tr>
<tr class="even">
<td style="text-align: left;">By Age</td>
</tr>
<tr class="odd">
<td style="text-align: left;">By Sex</td>
</tr>
<tr class="even">
<td style="text-align: left;">By Presence of Symptoms of Anxiety/Depression</td>
</tr>
<tr class="odd">
<td style="text-align: left;">By Race/Hispanic ethnicity</td>
</tr>
<tr class="even">
<td style="text-align: left;">By Education</td>
</tr>
<tr class="odd">
<td style="text-align: left;">By State</td>
</tr>
<tr class="even">
<td style="text-align: left;">By Disability status</td>
</tr>
<tr class="odd">
<td style="text-align: left;">By Gender identity</td>
</tr>
<tr class="even">
<td style="text-align: left;">By Sexual orientation</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>For the age group, there are 7 subgroups. For the education group, there are 4 subgroups.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Returning more (or less) than 1 row per `summarise()` group was deprecated in
dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
  always returns an ungrouped data frame and adjust accordingly.</code></pre>
</div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table 1d. List of Age Subgroups</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Age Subgroups</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">18 - 29 years</td>
</tr>
<tr class="even">
<td style="text-align: left;">30 - 39 years</td>
</tr>
<tr class="odd">
<td style="text-align: left;">40 - 49 years</td>
</tr>
<tr class="even">
<td style="text-align: left;">50 - 59 years</td>
</tr>
<tr class="odd">
<td style="text-align: left;">60 - 69 years</td>
</tr>
<tr class="even">
<td style="text-align: left;">70 - 79 years</td>
</tr>
<tr class="odd">
<td style="text-align: left;">80 years and above</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Returning more (or less) than 1 row per `summarise()` group was deprecated in
dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
  always returns an ungrouped data frame and adjust accordingly.</code></pre>
</div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table 1e. List of Education Subgroups</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Education Subgroups</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Less than a high school diploma</td>
</tr>
<tr class="even">
<td style="text-align: left;">High school diploma or GED</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Some college/Associate's degree</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bachelor's degree or higher</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>This dataset contains phase and time periods, but these measurements are not categorized by month or year. For the purpose of my time periods of interest, I have created a year and month category using the time periods provided in the dataset as well.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Table 2. List of Relevant Columns Examined</caption>
<colgroup>
<col style="width: 22%">
<col style="width: 77%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Name</th>
<th style="text-align: left;">Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Indicator</td>
<td style="text-align: left;">Needed Counseling or Therapy But Did Not Get It, Last 4 Weeks</td>
</tr>
<tr class="even">
<td style="text-align: left;">Group 1</td>
<td style="text-align: left;">Age</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group 2</td>
<td style="text-align: left;">Education</td>
</tr>
<tr class="even">
<td style="text-align: left;">Group 1 Subgroups</td>
<td style="text-align: left;">7 age subgroups</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group 2 Subgroups</td>
<td style="text-align: left;">4 education subgroups</td>
</tr>
<tr class="even">
<td style="text-align: left;">Time</td>
<td style="text-align: left;">Year, Month</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Value</td>
<td style="text-align: left;">Percent</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="exploratory-data-analysis-eda" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis-eda">Exploratory Data Analysis (EDA)</h3>
<p>To review, the EDA Checklist:</p>
<ol type="1">
<li><p>Formulate a question - See above.</p></li>
<li><p>Read in the data - See above.</p></li>
<li><p>Check the dimensions and headers and footers of the data - See above.</p></li>
<li><p>Check the variable types in the data - See above.</p></li>
<li><p>Take a closer look at some/all of the variables - See <strong>Exploratory Data Analysis</strong> below.</p></li>
<li><p>Validate with an external source - See <strong>Introduction</strong> above, <strong>Exploratory Data Analysis</strong> below.</p></li>
<li><p>Conduct some summary statistics to answer the initial question - See <strong>Exploratory Data Analysis, Results/Data Visualization</strong> below.</p></li>
<li><p>Make exploratory graphs - see <strong>Results/Data Visualization</strong> below.</p></li>
</ol>
<p>The next sections look at the Age and Education groups more closely.</p>
<section id="age" class="level4">
<h4 class="anchored" data-anchor-id="age">Age</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
     18 - 29 years      30 - 39 years      40 - 49 years      50 - 59 years 
               152                152                152                152 
     60 - 69 years      70 - 79 years 80 years and above 
               152                152                152 </code></pre>
</div>
</div>
<p>It is interesting how are all the counts are so perfect in each subgroup. However, upon consideration of the data, each time period of measurement has one record of each of the subgroups, and is not divided into data points for each individual that may have responded to the survey for each of the indicators. In a sense, the data provided in the dataset is not the raw data from the survey, but has already gone through some processing. To note, similar findings were observed for Education subgroups. For the purpose of my question, I am more interested in the values measured within each of these subgroups.</p>
<p>To start, I checked for any NA’s in my values for the Age subgroups.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   1.40    9.50   16.90   15.96   22.10   33.90     153 </code></pre>
</div>
</div>
<p>Looking at the dataset, it looks like the number of missing values are present for all Age subgroups. However, it can be noted that except for the Age subgroup of “80 years and above”, all are missing values in the time period labelled as “Phase -1”. To review, “Phase -1” indicates break times between every measured 4 week periods. For the purposes of the following data analysis, it is reasonable to remove these missing values in all “Phase -1” time points as no measures were actively performed during these times. The code used to do so is shown below. The Age subgroup of “80 years and above” however does contain other time Phases that appear to be truly missing values. In this case, replacing them with the relevant Age subgroup mean is reasonable. The code used to do this is also shown below. Some possible explanations include considerations that population may not have been as well accounted for in this dataset or there were no participants in this age range during select phases of measurement or recruitment. The specific details are difficult to identify as no explanation is conveyed by the CDC or NCHS in reviewed materials, though it is stated that participants were randomly selected for invitations to respond to survey materials.</p>
<p>While the methods used identifies all missing values within the Age subgroups of interest (including Indicators and other columns that may not be relevant to the current research question), it is worth examining these missing values in their entirety, as this lends to greater understanding and direction for future study.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Missing values found in subgroup: 18 - 29 years"
# A tibble: 5 × 17
  Indicator         Group State Subgroup Phase `Time Period` `Time Period Label`
  &lt;chr&gt;             &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt; &lt;chr&gt;              
1 Took Prescriptio… By A… Unit… 18 - 29… -1                1 Dec 22, 2020 - Jan…
2 Received Counsel… By A… Unit… 18 - 29… -1                1 Dec 22, 2020 - Jan…
3 Took Prescriptio… By A… Unit… 18 - 29… -1                1 Dec 22, 2020 - Jan…
4 Needed Counselin… By A… Unit… 18 - 29… -1                1 Dec 22, 2020 - Jan…
5 Took Prescriptio… By A… Unit… 18 - 29… -1                1 Mar 30 - Apr 13, 2…
# ℹ 10 more variables: `Time Period Start Date` &lt;date&gt;,
#   `Time Period End Date` &lt;chr&gt;, Value &lt;dbl&gt;, LowCI &lt;dbl&gt;, HighCI &lt;dbl&gt;,
#   `Confidence Interval` &lt;chr&gt;, `Quartile Range` &lt;chr&gt;,
#   `Suppression Flag` &lt;dbl&gt;, year &lt;int&gt;, month &lt;int&gt;
[1] "Missing values found in subgroup: 30 - 39 years"
# A tibble: 5 × 17
  Indicator         Group State Subgroup Phase `Time Period` `Time Period Label`
  &lt;chr&gt;             &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt; &lt;chr&gt;              
1 Took Prescriptio… By A… Unit… 30 - 39… -1                1 Dec 22, 2020 - Jan…
2 Received Counsel… By A… Unit… 30 - 39… -1                1 Dec 22, 2020 - Jan…
3 Took Prescriptio… By A… Unit… 30 - 39… -1                1 Dec 22, 2020 - Jan…
4 Needed Counselin… By A… Unit… 30 - 39… -1                1 Dec 22, 2020 - Jan…
5 Took Prescriptio… By A… Unit… 30 - 39… -1                1 Mar 30 - Apr 13, 2…
# ℹ 10 more variables: `Time Period Start Date` &lt;date&gt;,
#   `Time Period End Date` &lt;chr&gt;, Value &lt;dbl&gt;, LowCI &lt;dbl&gt;, HighCI &lt;dbl&gt;,
#   `Confidence Interval` &lt;chr&gt;, `Quartile Range` &lt;chr&gt;,
#   `Suppression Flag` &lt;dbl&gt;, year &lt;int&gt;, month &lt;int&gt;
[1] "Missing values found in subgroup: 40 - 49 years"
# A tibble: 5 × 17
  Indicator         Group State Subgroup Phase `Time Period` `Time Period Label`
  &lt;chr&gt;             &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt; &lt;chr&gt;              
1 Took Prescriptio… By A… Unit… 40 - 49… -1                1 Dec 22, 2020 - Jan…
2 Received Counsel… By A… Unit… 40 - 49… -1                1 Dec 22, 2020 - Jan…
3 Took Prescriptio… By A… Unit… 40 - 49… -1                1 Dec 22, 2020 - Jan…
4 Needed Counselin… By A… Unit… 40 - 49… -1                1 Dec 22, 2020 - Jan…
5 Took Prescriptio… By A… Unit… 40 - 49… -1                1 Mar 30 - Apr 13, 2…
# ℹ 10 more variables: `Time Period Start Date` &lt;date&gt;,
#   `Time Period End Date` &lt;chr&gt;, Value &lt;dbl&gt;, LowCI &lt;dbl&gt;, HighCI &lt;dbl&gt;,
#   `Confidence Interval` &lt;chr&gt;, `Quartile Range` &lt;chr&gt;,
#   `Suppression Flag` &lt;dbl&gt;, year &lt;int&gt;, month &lt;int&gt;
[1] "Missing values found in subgroup: 50 - 59 years"
# A tibble: 5 × 17
  Indicator         Group State Subgroup Phase `Time Period` `Time Period Label`
  &lt;chr&gt;             &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt; &lt;chr&gt;              
1 Took Prescriptio… By A… Unit… 50 - 59… -1                1 Dec 22, 2020 - Jan…
2 Received Counsel… By A… Unit… 50 - 59… -1                1 Dec 22, 2020 - Jan…
3 Took Prescriptio… By A… Unit… 50 - 59… -1                1 Dec 22, 2020 - Jan…
4 Needed Counselin… By A… Unit… 50 - 59… -1                1 Dec 22, 2020 - Jan…
5 Took Prescriptio… By A… Unit… 50 - 59… -1                1 Mar 30 - Apr 13, 2…
# ℹ 10 more variables: `Time Period Start Date` &lt;date&gt;,
#   `Time Period End Date` &lt;chr&gt;, Value &lt;dbl&gt;, LowCI &lt;dbl&gt;, HighCI &lt;dbl&gt;,
#   `Confidence Interval` &lt;chr&gt;, `Quartile Range` &lt;chr&gt;,
#   `Suppression Flag` &lt;dbl&gt;, year &lt;int&gt;, month &lt;int&gt;
[1] "Missing values found in subgroup: 60 - 69 years"
# A tibble: 5 × 17
  Indicator         Group State Subgroup Phase `Time Period` `Time Period Label`
  &lt;chr&gt;             &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt; &lt;chr&gt;              
1 Took Prescriptio… By A… Unit… 60 - 69… -1                1 Dec 22, 2020 - Jan…
2 Received Counsel… By A… Unit… 60 - 69… -1                1 Dec 22, 2020 - Jan…
3 Took Prescriptio… By A… Unit… 60 - 69… -1                1 Dec 22, 2020 - Jan…
4 Needed Counselin… By A… Unit… 60 - 69… -1                1 Dec 22, 2020 - Jan…
5 Took Prescriptio… By A… Unit… 60 - 69… -1                1 Mar 30 - Apr 13, 2…
# ℹ 10 more variables: `Time Period Start Date` &lt;date&gt;,
#   `Time Period End Date` &lt;chr&gt;, Value &lt;dbl&gt;, LowCI &lt;dbl&gt;, HighCI &lt;dbl&gt;,
#   `Confidence Interval` &lt;chr&gt;, `Quartile Range` &lt;chr&gt;,
#   `Suppression Flag` &lt;dbl&gt;, year &lt;int&gt;, month &lt;int&gt;
[1] "Missing values found in subgroup: 70 - 79 years"
# A tibble: 5 × 17
  Indicator         Group State Subgroup Phase `Time Period` `Time Period Label`
  &lt;chr&gt;             &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt; &lt;chr&gt;              
1 Took Prescriptio… By A… Unit… 70 - 79… -1                1 Dec 22, 2020 - Jan…
2 Received Counsel… By A… Unit… 70 - 79… -1                1 Dec 22, 2020 - Jan…
3 Took Prescriptio… By A… Unit… 70 - 79… -1                1 Dec 22, 2020 - Jan…
4 Needed Counselin… By A… Unit… 70 - 79… -1                1 Dec 22, 2020 - Jan…
5 Took Prescriptio… By A… Unit… 70 - 79… -1                1 Mar 30 - Apr 13, 2…
# ℹ 10 more variables: `Time Period Start Date` &lt;date&gt;,
#   `Time Period End Date` &lt;chr&gt;, Value &lt;dbl&gt;, LowCI &lt;dbl&gt;, HighCI &lt;dbl&gt;,
#   `Confidence Interval` &lt;chr&gt;, `Quartile Range` &lt;chr&gt;,
#   `Suppression Flag` &lt;dbl&gt;, year &lt;int&gt;, month &lt;int&gt;
[1] "Missing values found in subgroup: 80 years and above"
# A tibble: 5 × 17
  Indicator         Group State Subgroup Phase `Time Period` `Time Period Label`
  &lt;chr&gt;             &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt; &lt;chr&gt;              
1 Needed Counselin… By A… Unit… 80 year… 2                15 Sep 16 - Sep 28, 2…
2 Received Counsel… By A… Unit… 80 year… 2                17 Oct 14 - Oct 26, 2…
3 Needed Counselin… By A… Unit… 80 year… 3 (O…            18 Oct 28 - Nov 9, 20…
4 Received Counsel… By A… Unit… 80 year… 3 (O…            20 Nov 25 - Dec 7, 20…
5 Took Prescriptio… By A… Unit… 80 year… -1                1 Dec 22, 2020 - Jan…
# ℹ 10 more variables: `Time Period Start Date` &lt;date&gt;,
#   `Time Period End Date` &lt;chr&gt;, Value &lt;dbl&gt;, LowCI &lt;dbl&gt;, HighCI &lt;dbl&gt;,
#   `Confidence Interval` &lt;chr&gt;, `Quartile Range` &lt;chr&gt;,
#   `Suppression Flag` &lt;dbl&gt;, year &lt;int&gt;, month &lt;int&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Remove rows with Phase -1</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>data_filter <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Phase <span class="sc">!=</span> <span class="st">"-1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Replace missing values in Age subgroup "80 years and above"</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>age_subgrp_80_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(age_subgrp_80<span class="sc">$</span>Value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>age_subgrp <span class="ot">&lt;-</span> age_subgrp <span class="sc">%&gt;%</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Value =</span> <span class="fu">ifelse</span>(Subgroup <span class="sc">==</span> <span class="st">"80 years and above"</span> <span class="sc">&amp;</span> <span class="fu">is.na</span>(Value), age_subgrp_80_mean, Value))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The mean value within each of the 7 Age subgroups was reviewed.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 2
  Subgroup           mean_value
  &lt;chr&gt;                   &lt;dbl&gt;
1 18 - 29 years           19.8 
2 30 - 39 years           15.6 
3 40 - 49 years           11.8 
4 50 - 59 years            9.15
5 60 - 69 years            5.78
6 70 - 79 years            3.26
7 80 years and above       4.87</code></pre>
</div>
</div>
<p>A summary of the Age subgroups is shown below. Note there are no longer any missing values.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   1.40    5.10    9.60   10.05   14.80   23.10 </code></pre>
</div>
</div>
</section>
<section id="education" class="level4">
<h4 class="anchored" data-anchor-id="education">Education</h4>
<p>With regards to Education, a similar methodology was used as for Age. Similar to Age subgroups, the number of measured units was identical across all Education subgroups. Again, I checked for missing values, which were all again identified to be within the “Phase -1” time periods. For the purposes of the following data analysis, it is reasonable to again remove these missing values in all “Phase -1” time points. The code used to do this is identical to that described above with the Age subgroups.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Bachelor's degree or higher      High school diploma or GED 
                            152                             152 
Less than a high school diploma Some college/Associate's degree 
                            152                             152 </code></pre>
</div>
</div>
<p>To start, I checked for any NA’s in my values for the Education subgroups.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   5.60   10.50   15.05   16.40   22.00   30.00      80 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Missing values found in subgroup: Less than a high school diploma"
# A tibble: 5 × 17
  Indicator         Group State Subgroup Phase `Time Period` `Time Period Label`
  &lt;chr&gt;             &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt; &lt;chr&gt;              
1 Took Prescriptio… By E… Unit… Less th… -1                1 Dec 22, 2020 - Jan…
2 Received Counsel… By E… Unit… Less th… -1                1 Dec 22, 2020 - Jan…
3 Took Prescriptio… By E… Unit… Less th… -1                1 Dec 22, 2020 - Jan…
4 Needed Counselin… By E… Unit… Less th… -1                1 Dec 22, 2020 - Jan…
5 Took Prescriptio… By E… Unit… Less th… -1                1 Mar 30 - Apr 13, 2…
# ℹ 10 more variables: `Time Period Start Date` &lt;date&gt;,
#   `Time Period End Date` &lt;chr&gt;, Value &lt;dbl&gt;, LowCI &lt;dbl&gt;, HighCI &lt;dbl&gt;,
#   `Confidence Interval` &lt;chr&gt;, `Quartile Range` &lt;chr&gt;,
#   `Suppression Flag` &lt;dbl&gt;, year &lt;int&gt;, month &lt;int&gt;
[1] "Missing values found in subgroup: High school diploma or GED"
# A tibble: 5 × 17
  Indicator         Group State Subgroup Phase `Time Period` `Time Period Label`
  &lt;chr&gt;             &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt; &lt;chr&gt;              
1 Took Prescriptio… By E… Unit… High sc… -1                1 Dec 22, 2020 - Jan…
2 Received Counsel… By E… Unit… High sc… -1                1 Dec 22, 2020 - Jan…
3 Took Prescriptio… By E… Unit… High sc… -1                1 Dec 22, 2020 - Jan…
4 Needed Counselin… By E… Unit… High sc… -1                1 Dec 22, 2020 - Jan…
5 Took Prescriptio… By E… Unit… High sc… -1                1 Mar 30 - Apr 13, 2…
# ℹ 10 more variables: `Time Period Start Date` &lt;date&gt;,
#   `Time Period End Date` &lt;chr&gt;, Value &lt;dbl&gt;, LowCI &lt;dbl&gt;, HighCI &lt;dbl&gt;,
#   `Confidence Interval` &lt;chr&gt;, `Quartile Range` &lt;chr&gt;,
#   `Suppression Flag` &lt;dbl&gt;, year &lt;int&gt;, month &lt;int&gt;
[1] "Missing values found in subgroup: Some college/Associate's degree"
# A tibble: 5 × 17
  Indicator         Group State Subgroup Phase `Time Period` `Time Period Label`
  &lt;chr&gt;             &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt; &lt;chr&gt;              
1 Took Prescriptio… By E… Unit… Some co… -1                1 Dec 22, 2020 - Jan…
2 Received Counsel… By E… Unit… Some co… -1                1 Dec 22, 2020 - Jan…
3 Took Prescriptio… By E… Unit… Some co… -1                1 Dec 22, 2020 - Jan…
4 Needed Counselin… By E… Unit… Some co… -1                1 Dec 22, 2020 - Jan…
5 Took Prescriptio… By E… Unit… Some co… -1                1 Mar 30 - Apr 13, 2…
# ℹ 10 more variables: `Time Period Start Date` &lt;date&gt;,
#   `Time Period End Date` &lt;chr&gt;, Value &lt;dbl&gt;, LowCI &lt;dbl&gt;, HighCI &lt;dbl&gt;,
#   `Confidence Interval` &lt;chr&gt;, `Quartile Range` &lt;chr&gt;,
#   `Suppression Flag` &lt;dbl&gt;, year &lt;int&gt;, month &lt;int&gt;
[1] "Missing values found in subgroup: Bachelor's degree or higher"
# A tibble: 5 × 17
  Indicator         Group State Subgroup Phase `Time Period` `Time Period Label`
  &lt;chr&gt;             &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt; &lt;chr&gt;              
1 Took Prescriptio… By E… Unit… Bachelo… -1                1 Dec 22, 2020 - Jan…
2 Received Counsel… By E… Unit… Bachelo… -1                1 Dec 22, 2020 - Jan…
3 Took Prescriptio… By E… Unit… Bachelo… -1                1 Dec 22, 2020 - Jan…
4 Needed Counselin… By E… Unit… Bachelo… -1                1 Dec 22, 2020 - Jan…
5 Took Prescriptio… By E… Unit… Bachelo… -1                1 Mar 30 - Apr 13, 2…
# ℹ 10 more variables: `Time Period Start Date` &lt;date&gt;,
#   `Time Period End Date` &lt;chr&gt;, Value &lt;dbl&gt;, LowCI &lt;dbl&gt;, HighCI &lt;dbl&gt;,
#   `Confidence Interval` &lt;chr&gt;, `Quartile Range` &lt;chr&gt;,
#   `Suppression Flag` &lt;dbl&gt;, year &lt;int&gt;, month &lt;int&gt;</code></pre>
</div>
</div>
<p>The mean value within each of the 4 Education subgroups was reviewed.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  Subgroup                        mean_value
  &lt;chr&gt;                                &lt;dbl&gt;
1 Bachelor's degree or higher          10.6 
2 High school diploma or GED            8.75
3 Less than a high school diploma      10.5 
4 Some college/Associate's degree      13.5 </code></pre>
</div>
</div>
<p>A summary of the Education subgroups is shown below. Note there are no longer any missing values.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   6.90    9.30   10.80   10.84   12.05   15.10 </code></pre>
</div>
</div>
</section>
<section id="year" class="level4">
<h4 class="anchored" data-anchor-id="year">Year</h4>
<p>To review the year time points (2020, 2021, 2022), the number of measurements was also examined. Unlike that of Age and Education subgroups, the years had different number of measurements, as there were different time points in which the data began collection in the respective years, in addition to the offset measurements every 4 weeks with a break week in between (which has been filtered out due to the missing values during these breaks).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
2020 2021 2022 
2676 6332 1396 </code></pre>
</div>
</div>
<p>To check mean values for each year, I used a similar method to that used for Age and Education.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
   year mean_value
  &lt;int&gt;      &lt;dbl&gt;
1  2020       10.5
2  2021       11.3
3  2022       12.2</code></pre>
</div>
</div>
</section>
<section id="month" class="level4">
<h4 class="anchored" data-anchor-id="month">Month</h4>
<p>To review the month time points, the number of measurements was also examined. Unlike that of Age and Education subgroups, the months had slightly different number of measurements, as there were different time points in which the data began collection in the respective months, in part due to the offset measurements every 4 weeks with a break week in between (which has been filtered out due to the missing values during these breaks).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3    4    5    6    7    8    9   10   11   12 
 896  692 1300  912  592  592  412  928 1824  668  576 1012 </code></pre>
</div>
</div>
<p>To check mean values for each month, I used a similar method to that used above.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
   month mean_value
   &lt;int&gt;      &lt;dbl&gt;
 1     1      11.5 
 2     2      11.4 
 3     3      11.8 
 4     4      10.9 
 5     5       9.86
 6     6      10.3 
 7     7      12.2 
 8     8      11.0 
 9     9      10.9 
10    10      10.9 
11    11      11.4 
12    12      12.3 </code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="resultsdata-visualization" class="level2">
<h2 class="anchored" data-anchor-id="resultsdata-visualization">Results/Data Visualization</h2>
<section id="age-1" class="level3">
<h3 class="anchored" data-anchor-id="age-1">Age</h3>
<p>The general trend in age observed is that older age groups indicated fewer lacks in mental health care compared to younger age groups (See Figure 1.). The overall mean percent across all age groups was 10.05%. The ages 18-29 years old had the highest rates of lack of mental health care at 19.85%, and those 70-79 years old with the lowest rates at 3.26%. The one exception to the general decreasing trend with increasing age was for those 80 years and above, at 4.87%.</p>
<p>In term of temporal trends, it can be seen that lack of mental health care has generally increased from 2020 to 2022 across age groups (See Figure 2.). While each group continued to stay consistent with regards to greatest and least lack of mental health care (i.e.&nbsp;the 18-29 year old group stayed with the higher level of lack of mental health care in each year, the 70-79 year old group stayed with the lowest level), it can be observed that most groups have increasing percentage rate from 2020, through 2021, and into 2022. Some notable exceptions to this is again the 80 years and above cohort, which is observed to have a slight dip in 2021, though they continued on a similar upward trend in 2022. The 70-79 year old cohort also appears to have a relatively stable trend from 2020 to 2022, setting it apart from the other aged cohorts. Another point to note is that while all other age groups have a general increase in slope from 2021 to 2022, the 18-29 year old cohort did have a flattening slope during this time.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table 3. Summary of Average Percent of Individuals Lacking Mental Health Counseling or Therapy by Age Group</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Age Group</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Average Percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">18 - 29 years</td>
<td style="text-align: right;">19.848485</td>
</tr>
<tr class="even">
<td style="text-align: left;">30 - 39 years</td>
<td style="text-align: right;">15.566667</td>
</tr>
<tr class="odd">
<td style="text-align: left;">40 - 49 years</td>
<td style="text-align: right;">11.845455</td>
</tr>
<tr class="even">
<td style="text-align: left;">50 - 59 years</td>
<td style="text-align: right;">9.148485</td>
</tr>
<tr class="odd">
<td style="text-align: left;">60 - 69 years</td>
<td style="text-align: right;">5.775758</td>
</tr>
<tr class="even">
<td style="text-align: left;">70 - 79 years</td>
<td style="text-align: right;">3.263636</td>
</tr>
<tr class="odd">
<td style="text-align: left;">80 years and above</td>
<td style="text-align: right;">4.868449</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image</code></pre>
</div>
</div>
</section>
<section id="education-1" class="level3">
<h3 class="anchored" data-anchor-id="education-1">Education</h3>
<p>There is no distinct trend observed in education subgroups with regards to lack of mental health care, with fluctuations across education level (See Figure 3.). The overall mean percent across all education groups was 10.8%. Those with Less than a high school diploma had a 10.55% lack of mental health care, High school diploma or GED at the lowest value at 8.75%, Some college/Associate’s at the highest value at 13.47%, and Bachelor’s degree or higher at 10.61%.</p>
<p>In term of temporal trends, it can be seen that lack of mental health care has generally increased from 2020 to 2022 across education levels (See Figure 4.). While to order generally appeared to stay consistent in order through 2020 to 2021, in 2022 the Less than high school diploma cohort exceeded the Bachelor’s degree of higher cohort in percent of lack of mental health care. It is of potential interest in that the slope for those with High school diploma or GED decreased from 2021 to 2022, while the slope of other education level cohorts did have a consistent increase from 2020 to 2022.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table 4. Summary of Average Percent of Individuals Lacking Mental Health Counseling or Therapy by Education Level</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Education Level</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Average Percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Less than a high school diploma</td>
<td style="text-align: right;">10.545454</td>
</tr>
<tr class="even">
<td style="text-align: left;">High school diploma or GED</td>
<td style="text-align: right;">8.748485</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Some college/Associate's degree</td>
<td style="text-align: right;">13.472727</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bachelor's degree or higher</td>
<td style="text-align: right;">10.609091</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image</code></pre>
</div>
</div>
</section>
<section id="year-and-month" class="level3">
<h3 class="anchored" data-anchor-id="year-and-month">Year and Month</h3>
<p>The overall year average percents appears consistent with what was observed for both Age and Education subgroups in that there is a positive trend across the years for lack of mental health care (See Figure 5.). In 2020, an average of 10.54% lacked mental health care, with an increase to 11.27% in 2021, and at 12.20% in 2022.</p>
<p>The overall month average percent trend appears to be positive from January to December, though noticeably large fluctuations from month to month are observed (See Figure 6.). May was observed to be the month with the lowest percent lack of mental health care at 9.86%, with December the highest at 12.27%.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Summary of Average Percent of Individuals Lacking Mental Health Counseling or Therapy by Year</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Year</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Average Percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2020</td>
<td style="text-align: right;">10.54118</td>
</tr>
<tr class="even">
<td style="text-align: right;">2021</td>
<td style="text-align: right;">11.27309</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2022</td>
<td style="text-align: right;">12.20470</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Final_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lubridate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    date, intersect, setdiff, union</code></pre>
</div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Summary of Average Percent of Individuals Lacking Mental Health Counseling or Therapy by Month</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Month</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Average Percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">January</td>
<td style="text-align: right;">11.466518</td>
</tr>
<tr class="even">
<td style="text-align: left;">February</td>
<td style="text-align: right;">11.425694</td>
</tr>
<tr class="odd">
<td style="text-align: left;">March</td>
<td style="text-align: right;">11.795379</td>
</tr>
<tr class="even">
<td style="text-align: left;">April</td>
<td style="text-align: right;">10.881858</td>
</tr>
<tr class="odd">
<td style="text-align: left;">May</td>
<td style="text-align: right;">9.860274</td>
</tr>
<tr class="even">
<td style="text-align: left;">June</td>
<td style="text-align: right;">10.306849</td>
</tr>
<tr class="odd">
<td style="text-align: left;">July</td>
<td style="text-align: right;">12.170000</td>
</tr>
<tr class="even">
<td style="text-align: left;">August</td>
<td style="text-align: right;">10.987879</td>
</tr>
<tr class="odd">
<td style="text-align: left;">September</td>
<td style="text-align: right;">10.934292</td>
</tr>
<tr class="even">
<td style="text-align: left;">October</td>
<td style="text-align: right;">10.851748</td>
</tr>
<tr class="odd">
<td style="text-align: left;">November</td>
<td style="text-align: right;">11.368750</td>
</tr>
<tr class="even">
<td style="text-align: left;">December</td>
<td style="text-align: right;">12.270130</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions</h2>
<p>This data showed that since 2020, lack of mental health care has been on a generally increasing trend across all examined groups (Age, Education level), with mild differences. This is concerning but perhaps not unexpected given potential lag time between the start of the pandemic in 2019, leading to possible increase in incidence of mental health issues, time between symptoms and clinical diagnosis, stigma of mental health illness, and then time to seek and receive care. Certainly, insurance and other systemic health delivery aspects play a role as well. Multiple factors must be considered for the reason behind this increase, and future surveying and research are necessary.</p>
<p>It is notable that the 18-29 year old Age group have consistently the highest rates of lack of mental health care for any age group examined. Possible explanations may include the school experience for most individuals in this cohort, as well as job market uncertainty, especially during the pandemic where mass layoffs occurred and lack of financial security was a common experience. More insight into these shared experiences may be worthwhile research topics, and potential aspects to include and address in care methods.</p>
<p>Examining Education level, those with High school diploma or GED were consistently lowest for lack of mental health care, while Some college/Associate’s degree was consistently the highest. It is uncertain why this might be the case, as neither would be categorized as the greatest or lowest level of education in the levels measured in this dataset, so education may be a confounding factor in levels of mental health care access. Another thought may be that both higher and lower levels of education (i.e., Bachelor’s degree of higher, Less than a high school diploma) may have both protective and risk factors for mental health illness and/or healthcare access, resulting in a more buffered level of received care in the range of education levels measured. Further research is needed to determine this observation, and consideration of social networks, environmental exposures, and other stressors are warranted.</p>
<p>With regards to the monthly fluctuations, one potential explanation may be related to school year schedules and holidays — in general, it may be that during the summer holidays (July) and winter holidays (November - January), individuals may traditionally have group and family gatherings which may have been restricted during the pandemic as well as a setting of high-stress, leading to increasing need for mental health care as well as potential unwillingness to seek related care. Typically, March - May is leading up to the end of the school year and start of the summer holidays/season, which may be a mental relief or positive mental expectation for individuals, leading to lower need for mental health care or potential motivation to seek care.</p>
<p>To conclude, this data showed a positive trend in lack of mental health care across groups. Further research is recommended to examine exact causes and influences on this trend.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p><em>Mental health care in the last 4 weeks | Data | Centers for Disease Control and Prevention</em>. (2022, November 28). https://data.cdc.gov/NCHS/Mental-Health-Care-in-the-Last-4-Weeks/yni7-er2q</p>
<p>Centers for Disease Control and Prevention. (2022, July 20). <em>Mental health care - household pulse survey - covid-19</em>. Centers for Disease Control and Prevention. https://www.cdc.gov/nchs/covid19/pulse/mental-health-care.htm</p>
<p>Khan, K. S., Mamun, M. A., Griffiths, M. D., &amp; Ullah, I. (2022). The Mental Health Impact of the COVID-19 Pandemic Across Different Cohorts. <em>International journal of mental health and addiction</em>, <em>20</em>(1), 380–386. https://doi.org/10.1007/s11469-020-00367-0</p>
<p>Christoffersen LA, Helenius D, Schwinn M, Erikstrup C, Hjalgrim H, Nissen J, Banasik K, Nielsen K, Kaspersen KA, Dinh KM, Bruun MT, Ostrowski SR, Sækmose S, Hansen TF, Werge T, Didriksen M, Pedersen OB. Experience of loneliness during the COVID-19 pandemic: a cross-sectional study of 50 968 adult Danes. BMJ Open. 2023 Apr 26;13(4):e064033. doi: 10.1136/bmjopen-2022-064033. PMID: 37185636; PMCID: PMC10151242.</p>
<p>Pakpour AH, Griffiths MD. The fear of COVID-19 and its role in preventive behaviors. Journal of Concurrent Disorders. 2020;2(1):58–63. doi:&nbsp;10.54127/WCIC8036.</p>
<p>Ahorsu, D. K., Lin, C. Y., Imani, V., Saffari, M., Griffiths, M. D., &amp; Pakpour, A. H. (2020). The fear of COVID-19 scale: Development and initial validation. International Journal of Mental Health and Addiction. 10.1007/s11469-020-00270-8.</p>
<p>Sakib, N., Mamun, M. A., Bhuiyan, A. I., Hossain, S., Al Mamun, F., Hosen, I., et al.&nbsp;(2020). Psychometric validation of the Bangla fear of COVID-19 scale: confirmatory factor analysis and Rasch analysis. International Journal of Mental Health and Addiction. 10.1007/s11469-020-00289-x.</p>
<p>Mills, D. J., Petrovic, J., Mettler, J., Hamza, C. A., &amp; Heath, N. L. (2022). The good, the bad, and the mixed: Experiences during COVID-19 among an online sample of adults. <em>PloS one</em>, <em>17</em>(6), e0269382. https://doi.org/10.1371/journal.pone.0269382</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>